Test workflow

diff --git a/.github/workflows/enforce-labels.yml b/.github/workflows/enforce-labels.yml
--- a/.github/workflows/enforce-labels.yml
+++ b/.github/workflows/enforce-labels.yml
@@ -1,12 +1,24 @@
-name: Enforce PR labels
+name: Check do not merge
 
 on:
+  # Check label at every push in a feature branch
+  push:
+    branches-ignore:
+      - prod
+      - preprod
+  # Check label during the lifetime of a pull request
   pull_request:
-    types: [labeled, unlabeled, opened, edited, synchronize]
+    types:
+    - opened
+    - labeled
+    - unlabeled
+
 jobs:
-  enforce-label:
+  fail-for-do-not-merge:
+    if: contains(github.event.pull_request.labels.*.name, 'DO NOT MERGE')
     runs-on: ubuntu-latest
     steps:
-    - uses: yogevbd/enforce-label-action@2.2.0
-      with:
-        BANNED_LABELS: "DO NOT MERGE"
+      - name: Fail if PR is labeled with DO NOT MERGE
+        run: |
+          echo "This PR can't be merged, due to the 'do not merge' label."
+          exit 1
